development:
  sessions:
    default:
      database: dsa_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false 
test:
  sessions:
    default:
      database: dsa_test
      hosts:
        - localhost:27017
<% uri = URI.parse("ENV['MONGOHQ_URL']") %>
production:
  sessions:
    default:
      database: <%= uri.path.sub('/', '') %>
      username: <%= uri.user %>
      password: <%= uri.password %>
      hosts:
        - <%= uri.host %>:<%= uri.port %>
  options:
    raise_not_found_error: false