development:
  sessions:
    default:
      database: dsa_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: dsa_test
      hosts:
        - localhost:27017